# Generated by Django 4.1.1 on 2022-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitles',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
