# Generated by Django 4.1.1 on 2022-09-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0004_homepage_rtfbody_alter_homepage_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
