# Generated by Django 4.1.1 on 2022-09-20 08:26

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', wagtail.blocks.RichTextBlock()), ('imgblock', wagtail.images.blocks.ImageChooserBlock()), ('youtubeblock', wagtail.embeds.blocks.EmbedBlock())], blank=True, use_json_field=None),
        ),
    ]
